kripra/protected/controllers/MainController.php
<?php

class MainController extends Controller {

    /**
     * Declares class-based actions.
     */
    public function actions() {
        return array(
            'page' => array(
                'class' => 'CViewAction',
            ),
        );
    }

    public function actionIndex() {

        $this->render('index');
    }

    public function actionError() {
        if ($error = Yii::app()->errorHandler->error) {
            if (Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', array('error' => $error));
        }
    }

    public function actionLogout() {
        Yii::app()->user->logout();
        $this->redirect(Yii::app()->homeUrl);
    }
}

kripra/protected/controllers/WalletController.php
<?php

Yii::import('application.controllers.AccountController');

class WalletController extends AccountController {

    private $_wallet;
    private $_currency_action;

    public function beforeAction($action) {
        $this->_user->createAllWallets();

        $currency = Yii::app()->getRequest()->getQuery('currency');


        if (!empty($currency)) {
            $wallets = $this->_user->wallets;

            foreach ($wallets as $w) {
                if ($w->currency == $currency) {
                    $this->_wallet = $w;
                }
            }
        }

        if (!empty($this->_wallet) && empty($this->_currency_action)) {
            $this->_currency_action = CurrencyAction::getAction($this->_wallet->currency);
        }

        return parent::beforeAction($action);
    }

    public function actionIndex() {

        $history = History::model()->with('history_amount')->findAllByAttributes(array('user'=>$this->_user->id));
        $this->render('index', array('wallets' => $this->_user->wallets, 'history' => $history));
    }

    public function actionMain() {
        $history = History::model()->with(array('history_amount' => array('joinType' => 'INNER JOIN',
                    'condition' => 'history_amount.currency=:currency',
                    'params' => array(':currency' => $this->_wallet->currency))))->findAll();

        $this->render('main', array('wallet' => $this->_wallet, 'history' => $history));
    }

    public function actionAddfunds() {
        $result = $this->_currency_action->addFunds($this->_wallet, $form_model);

        if ($result) {

            $history = new History();
            $history->type = 'addfunds';
            $history->user = $this->_user->id;
            if ($history->save()) {
                $historyAmount = new HistoryAmount;
                $historyAmount->currency = $this->_wallet->currency;
                $historyAmount->amount = $form_model->amount;
                $historyAmount->history = $history->id;
                if (!$historyAmount->save()) {
                    Yii::log("Cannot save addfunds history amount", "error");
                }
            }

            Yii::app()->user->setFlash('success', Yii::t('app', 'Addfunds successfull'));
            $this->redirect(Yii::app()->createUrl("wallet/main", array('currency' => $this->_wallet->currency)));
            Yii::app()->end();
        }

        $this->render($this->_currency_action->getAddFundsView(), array('wallet' => $this->_wallet,
            'data' => $result,
            'model' => $form_model));
    }

    public function actionWithdraw() {
        $result = $this->_currency_action->withdraw($this->_wallet, $form_model);
        if ($result) {

            $history = new History();
            $history->type = 'withdraw';
            $history->user = $this->_user->id;
            if ($history->save()) {
                $historyAmount = new HistoryAmount;
                $historyAmount->currency = $this->_wallet->currency;
                $historyAmount->amount = $form_model->amount;
                $historyAmount->history = $history->id;
                if (!$historyAmount->save()) {
                    Yii::log("Cannot save withdraw history amount", "error");
                }
            }

            Yii::app()->user->setFlash('success', Yii::t('app', 'Witdraw successfull'));
            $this->redirect(Yii::app()->createUrl("wallet/main", array('currency' => $this->_wallet->currency)));
            Yii::app()->end();
        }

        $this->render($this->_currency_action->getWithdrawView(), array('wallet' => $this->_wallet,
            'data' => $result,
            'model' => $form_model));
    }

}

?>

kripra/protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

kripra/protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

kripra/protected/views/layouts/mail.php
<html>
<head>
	<meta content="text/html; charset=UTF-8" http-equiv="content-type">
</head>
<table cellspacing="0" cellpadding="10" style="color:#666;font:13px Arial;line-height:1.4em;width:100%;">
	<tbody>
		<tr>
            <td style="color:#4D90FE;font-size:22px;border-bottom: 2px solid #4D90FE;">
				<?php echo CHtml::encode(Yii::app()->name); ?>
            </td>
		</tr>
		<tr>
            <td style="color:#777;font-size:16px;padding-top:5px;">
            	<?php if(isset($data['description'])) echo $data['description'];  ?>
            </td>
		</tr>
		<tr>
            <td>
				<?php echo $content ?>
            </td>
		</tr>
	</tbody>
</table>
</body>
</html>

kripra/protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="language" content="tr" />

        <!-- blueprint CSS framework -->
        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
        <!--[if lt IE 8]>
        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
        <![endif]-->

        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

        <title><?php echo CHtml::encode($this->pageTitle); ?></title>
    </head>

    <body>
        <?php
        $flashMessages = Yii::app()->user->getFlashes();
        if ($flashMessages) {
            echo '<ul class="flashes">';
            foreach ($flashMessages as $key => $message) {
                echo '<li><div class="flash-' . $key . '">' . $message . "</div></li>\n";
            }
            echo '</ul>';
        }
        ?>

        <div class="container" id="page">

            <div id="header">
                <div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
            </div><!-- header -->

            <div id="mainmenu">
                <?php
                $this->widget('zii.widgets.CMenu', array(
                    'items' => array(
                        array('label' => Yii::t('app','Home'), 'url' => array('/wallet/index')),
                        array('label' => Yii::t('app','About'), 'url' => array('/main/page', 'view' => 'about')),
                        array('label' => Yii::t('app','Login'), 'url' => array('/login'), 'visible' => Yii::app()->user->isGuest),
                        array('label' => Yii::t('app','Signup'), 'url' => array('/signup'), 'visible' => Yii::app()->user->isGuest),
                        array('label' => Yii::t('app','Logout'). '(' . Yii::app()->user->name . ')', 'url' => array('/main/logout'), 'visible' => !Yii::app()->user->isGuest)
                    ),
                ));
                ?>
            </div>


<?php echo $content; ?>

            <div class="clear"></div>

            <div id="footer">
               
            </div><!-- footer -->

        </div><!-- page -->

    </body>
</html>